version: '3.8'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"
    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
           - "9092:9092"
           - "9093:9093"            
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, SSL://localhost:9093
            KAFKA_SSL_KEYSTORE_FILENAME: kafka_server.jks
            KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore.creds
            KAFKA_SSL_KEY_CREDENTIALS: keystore.creds
            KAFKA_SSL_TRUSTSTORE_FILENAME: truststore.jks
            KAFKA_SSL_TRUSTSTORE_CREDENTIALS:  truststore.creds
            KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
            KAFKA_SSL_CLIENT_AUTH: 'required'
        volumes:
            - "D:/Programing/Git/Micro_Services-Security/Microservices_Security_Practice_08_reactive/certs:/etc/kafka/secrets"       