apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: orders-req-authn-policy
  namespace: "security"
spec:
  selector:
    matchLabels:
      app: orders
  jwtRules:
  - issuer: "sts.ecomm.com"
    audiences:
    - "*.ecomm.com"
    jwksUri: "https://raw.githubusercontent.com/microservices-security-in-action/samples/master/chapter12/sample04/jwtkey.jwk"
    forwardOriginalToken: true 
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: orders-services-policy
 namespace: "security"
spec:
 selector:
   matchLabels:
     app: orders
 action: DENY   
 rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: inventory-req-authn-policy
  namespace: "security"  
spec:
  selector:
    matchLabels:
      app: inventory
  jwtRules:
  - issuer: "sts.ecomm.com"
    audiences:
    - "*.ecomm.com"
    jwksUri: "https://raw.githubusercontent.com/microservices-security-in-action/samples/master/chapter12/sample04/jwtkey.jwk" 
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: inventory-services-policy
 namespace: "security"
spec:
 selector:
   matchLabels:
     app: inventory
 action: DENY    
 rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]      
    
    


     
    
    