apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "orders-request-auth"
  namespace: security
spec:
  selector:
    matchLabels:
            app: orders
  jwtRules:
  - issuer: "sts.ecomm.com"
    jwksUri: "https://raw.githubusercontent.com/microservices-security-in-action/samples/master/chapter12/sample04/jwtkey.jwk"
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "inventory-request-auth"
  namespace: security
spec:
  selector:
    matchLabels:
            app: inventory
  jwtRules:
  - issuer: "sts.ecomm.com"
    jwksUri: "https://raw.githubusercontent.com/microservices-security-in-action/samples/master/chapter12/sample04/jwtkey.jwk"
     